### ISSUE TITLE
Monochrome book whose pages get inverted after running pdfsizeopt

### ISSUE THREAD

**Issue by rbrito** [pts/pdfsizeopt#13] opened 2017-04-07 07:18 UTC
Hi, @pts.

I have some (actually, a lot) of files where pdfsizeopt misbehaves. The most recent of these is a page with only black and white pages where pdfsizeopt turns the pages from black text on a white background to white text on a black background, which is kind of unexpected.

I'm running pdfsizeopt with the following options:

```
pdfsizeopt --use-pngout=no --use-multivalent=no file.pdf
```

I suspect that the problem lies with ghostscript extracting the PNG files from the PDF (I pressed Ctrl-Z while the PNG files were being created and fired up the graphical viewer Eye of MATE and the pictures were already with a black background). I'm using everything from Ubuntu's zesty distribution (I can give you the precise versions if you want).

Since the file is copyrighted, I can send it directly to you if you want. In fact, I may send you many other files and the problems that pdfsizeopt has with them.

Thanks,

Rogério Brito.

**Comment by pts** [comment] 2017-04-07 15:23
Image processing errors should be relatively easy to fix in general.

You may want to crop the image (i.e. to 5x5 pixels) before you can attach it here, to avoid copyright issues.

**Comment by pts** [comment] 2017-06-09 13:31
Do you have any images which you can share, so that I can diagnose the problem in pdfsizeopt? If not, I'll close this issue, because I'm not able to reproduce the errors.

**Comment by rbrito** [comment] 2017-06-09 14:57
I will send you a copy of the book privately.

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

Em 9 de jun de 2017 10:32, "Péter Szabó" <notifications@github.com>
escreveu:

**Comment by pts** [comment] 2017-06-12 12:14
Still waiting for the PDF.

**Comment by pts** [comment] 2017-06-26 15:29
This is a duplicate of https://github.com/pts/pdfsizeopt/issues/20. Closing this, because the other bug has some example PDF files which trigger the buggy behavior.

**Closed by pts** 2017-06-26 15:29 UTC
