### ISSUE TITLE
Can't concatenate files into after pdfsizeopt

### ISSUE THREAD

**Issue by pda12** [pts/pdfsizeopt#118] opened 2019-06-18 11:34 UTC
After using pdfsizeopt to optimize a pdf successfully I can't cat any pdf into the optimized file.  I'm using pdftk to cat them in.  The error returned is "file not found".  Even using pdf-shuffler the cat'd file can't be saved.   Any ideas how to solve this?

**Comment by pts** [comment] 2019-06-18 13:31
Please attach the input and output PDF files of pdfsizeopt to this bug, please copy-paste the console input and output and the PDF output file of pdftk as well.

**Comment by pts** [comment] 2023-02-23 02:53
Closing this since the required files to reproduce this bug were not attached.

**Closed by pts** 2023-02-23 02:53 UTC
