### ISSUE TITLE
Type1CParser failure

### ISSUE THREAD

**Issue by lemzwerg** [pts/pdfsizeopt#100] opened 2018-10-19 08:55 UTC
[pdfsizeopt version dc08a10c02d20f984d3a21ecad5e77bd6fa86563]

Executing
```
PATH=/home/wl/pdfsizeopt:$PATH pdfsizeopt.py --v=999 zzz.pdf
```
using the attached file gives
```
info: This is pdfsizeopt ZIP rUNKNOWN size=68657.
info: prepending to PATH: /home/wl/git/pdfsizeopt/pdfsizeopt
info: loading PDF from: zzz.pdf
info: loaded PDF of 176567 bytes
info: separated to 68 objs + xref + trailer
info: parsed 68 objs
info: eliminated 3 unused objs, depth=9
info: found 0 Type1 fonts loaded
info: found 8 Type1C fonts loaded
info: writing Type1CParser (43911 font bytes) to: psotmp.31794.conv.parse.tmp.ps
info: using Ghostscript TMPDIR=. TEMP=. gs: GPL Ghostscript 9.25 (2018-09-13)
info: executing Type1CParser with Ghostscript: TMPDIR=. TEMP=. gs -q -P- -dNOPAUSE -dBATCH -sDEVICE=nullpage -sDataFile=psotmp.31794.conv.parsedata.tmp.ps -f psotmp.31794.conv.parse.tmp.ps
Error: /invalidaccess in --forall--
Operand stack:
   --nostringval--   FontSetInit   --nostringval--   0   --nostringval--   --nostringval--
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1999   1   3   %oparray_pop   1998   1   3   %oparray_pop   1982   1   3   %oparray_pop   1868   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--
Dictionary stack:
   --dict:977/1684(ro)(G)--   --dict:0/20(G)--   --dict:97/200(L)--
Current allocation mode is local
Current file position is 4254
GPL Ghostscript 9.25: Unrecoverable error, exit code 1
fatal: Type1CParser failed, status=0x100
```
[zzz.pdf](https://github.com/pts/pdfsizeopt/files/2495086/zzz.pdf)

**Comment by pts** [comment] 2018-10-19 14:30
Thank you for reporting this!

Excerpt from the console output:

```
info: using Ghostscript TMPDIR=. TEMP=. gs: GPL Ghostscript 9.25 (2018-09-13)
```

You may be getting the error because you are using Ghostscript 9.25. Please install pdfsizeopt as described in the README (https://github.com/pts/pdfsizeopt/), and you will get Ghostscript 9.05 and 9.10, which will most likely succeed.

**Comment by lemzwerg** [comment] 2018-10-20 05:06
I'm rather sure that this will fix it (no time to test it right now).  Note that the used PDF creation pipeline is as follows:

*  *n* × calling lilypond → *n* PDFs
* 1 × calling XeLaTeX including *n* PDFs → intermediate PDF
* Calling pstopdf on intermediate PDF → final PDF

pstopdf is used to fill in the font resources that are intentionally omitted in the lilypond step with a command line option; this avoids early, multiple subsetting of lilypond notation fonts, leaving the job rather to GS which enormously reduces the size of the final PDF.

IIRC, due to other problems with earlier GS versions, lilypond needs a more recent version than 9.10. 

I interpret your answer that you suspect a bug in GS.  Can you point to a GS bug report that describes the above issue?

**Comment by pts** [comment] 2018-10-22 10:52
> lilypond needs a more recent version than 9.10.

This will work. Feel free to use any version of Ghostscript for lilypond, pstopdf and other tools. But to make it work, please install pdfsizeopt as indicated in the README (https://github.com/pts/pdfsizeopt/). pdfsizeopt has its own copy of Ghostscript (version 9.05 or 9.10), which doesn't interfere with the Ghostscript installed to the system.

> I interpret your answer that you suspect a bug in GS. Can you point to a GS bug report that describes the above issue?

There is an incompatibility between pdfsizeopt and newer versions of Ghostscript, which I didn't have time to investigate yet. If anyone has more time or information, please comment on this bug.

**Comment by pts** [comment] 2018-12-17 15:15
This is a duplicate of https://github.com/pts/pdfsizeopt/issues/97 , let's continue the discussion there.

**Closed by pts** 2018-12-17 15:15 UTC
