### ISSUE TITLE
Files processed with pdfsizeopt become unreadable by qpdf and pdftk

### ISSUE THREAD

**Issue by rbrito** [pts/pdfsizeopt#57] opened 2017-10-12 05:19 UTC
Dear @pts,

Many files after being processed by pdfsizeopt become unreadable by qpdf and by pdftk for further modification/inspection. Here is what I get:

```
$ qpdf MASTERING_TEXT_MINING_WITH_R-9781783551811.pso.pdf foo.pdf
getStreamData called on unfilterable stream
$ 
```
pdftk gives a more cryptic message, telling us that the file couldn't be found (but it is there, I assure you):

```
$ pdftk MASTERING_TEXT_MINING_WITH_R-9781783551811.pso.pdf output foo.pdf
Error: Unable to find file.
Error: Failed to open PDF file: 
   MASTERING_TEXT_MINING_WITH_R-9781783551811.pso.pdf
Errors encountered.  No output created.
Done.  Input errors, so no output created.
$
```

Are the files that result from pdfsizeopt non-compliant or do both qpdf and pdftk have a bug with them? The file that was processed above came straight from Packt Publishing, in one of their free book downloads...

I simply processed the file in question with: `--use-pngout=no --use-multivalent=no --do-optimize-images=no`.

I will send you a link to the original privately.

Thanks,

Rogério Brito.

**Comment by pts** [comment] 2017-10-12 09:55
Thank you for reporting this!

I can reproduce these errors with both qpdf and pdftk, but not with gs, google-chrome or evince. It looks like the xref stream is the culprit:

* bad qpdf, bad pdftk, good gs, good google-chrome, good evince: `pdfsizeopt --do-optimize-images=no --do-optimize-fonts=no --do-generate-xref-stream=yes --do-generate-object-stream=no MASTERING_TEXT_MINING_WITH_R-9781783551811.pdf`
* good qpdf, good pdftk, good gs, good google-chrome, good evince: `pdfsizeopt --do-optimize-images=no --do-optimize-fonts=no --do-generate-xref-stream=no --do-generate-object-stream=no MASTERING_TEXT_MINING_WITH_R-9781783551811.pdf`

After some further digging, it looks like both qpdf and pdftk have problems decompressing a `/Type /XRef` obj if it has a `/Predictor`. In more detail:

* good (no predictor): `11974 0 obj<</Filter/FlateDecode/Info 11310 0 R/Length 32318/Root 11621 0 R/Size 11975/Type/XRef/W[0 3 0]>>stream`
* bad (predictor 2): `11974 0 obj<</DecodeParms<</Predictor 2/Colors 3/Columns 11975>>/Filter/FlateDecode/Info 11310 0 R/Length 9770/Root 11621 0 R/Size 11975/Type/XRef/W[0 3 0]>>stream`
* bad (predictor 10): `11974 0 obj<</DecodeParms<</Predictor 10/Columns 3>>/Filter/FlateDecode/Info 11310 0 R/Length 10371/Root 11621 0 R/Size 11975/Type/XRef/W[0 3 0]>>stream`

After successful decompression, the data size should be 35925 bytes, and SHA-1 of the data should be `c13ee3dc8e2cc27231bbbcd5a45a7e31af9fcf51` in all 3 cases above. Here are the full compressed objects (including their `stream`): [flate_objects_57.zip](https://github.com/pts/pdfsizeopt/files/1378864/flate_objects_57.zip).

I think these are bugs in both qpdf 6.0.0 and pdftk, please report these bugs in their bug trackers, and feel free to redirect them here if they some input data to reproduce the bugs.

I'm closing this issue, because it looks like pdfsizeopt generates valid and correct PDF, and there is nothing to fix in pdfsizeopt.

**Closed by pts** 2017-10-12 09:55 UTC
