### ISSUE TITLE
Numerous missing glyphs

### ISSUE THREAD

**Issue by teepeemm** [pts/pdfsizeopt#12] opened 2017-03-28 21:59 UTC
I've had trouble with math symbols disappearing from my document.  I've trimmed it down to the following, which has many symbols disappearing, not just math symbols.  I'm compiling these two documents with XeLaTeX and then running
`python relpath/pdfsizeopt --use-pngout=no --use-jbig2=no --use-multivalent=no myfile.pdf`
In the output, all letters are gone, the decimal period is gone, scriptsize numbers are gone, and textsize 0123456789 has become qrs76t32uv.  What I find strange is that the output pso file is ok if I do either of the following:
1. Use pdfLaTeX for either or both TeX files
2. Remove either of the two images

Is there a way I can keep all of the symbols?

This is possibly related to #11 (and indeed using `--do-unify-fonts=no` gives the correct output), but my purpose in using pdfsizeopt is to remove duplicate fonts from the included pdf.

[included.tex.txt](https://github.com/pts/pdfsizeopt/files/877186/included.tex.txt)
[myfile.tex.txt](https://github.com/pts/pdfsizeopt/files/877189/myfile.tex.txt)
[myfile.pdf](https://github.com/pts/pdfsizeopt/files/877182/myfile.pdf)
[myfile.pso.pdf](https://github.com/pts/pdfsizeopt/files/877196/myfile.pso.pdf)

**Comment by pts** [comment] 2017-03-29 00:14
Thank you for reporting this bug and attaching the relevant example files to reproduce.

Please attach more files:

1. myfile_with_pdflatex.pdf and myfile_with_pdflatex.pso.pdf
2. myfile_without_image1.pdf and myfile_without_image1.pso.pdf

Based on that I should be able to take a look how these files are different from myfile.pso.pdf, and maybe I'll be able to discover some incorrect dict value, and I can fix it. I can't promise that, but it's worth trying.

**Comment by teepeemm** [comment] 2017-03-29 16:00
Here you go.  Thanks for trying.

[myfile_with_pdflatex.pdf](https://github.com/pts/pdfsizeopt/files/879636/myfile_with_pdflatex.pdf)
[myfile_with_pdflatex.pso.pdf](https://github.com/pts/pdfsizeopt/files/879639/myfile_with_pdflatex.pso.pdf)
[myfile_without_image1.pdf](https://github.com/pts/pdfsizeopt/files/879638/myfile_without_image1.pdf)
[myfile_without_image1.pso.pdf](https://github.com/pts/pdfsizeopt/files/879637/myfile_without_image1.pso.pdf)

**Comment by pts** [comment] 2017-06-12 12:29
Thank you for reporting this bug and providing details!

Indeed, this looks like a bug in the font unification of pdfsizeopt. Until the bug is fixed, please use `--do-unify-fonts=no` to prevent the dropping of glyphs.

The behavior of `myfile_without_image1.pso.pdf` is expected, because there are no fonts to unify in `myfile_without_image1.pdf`, thus front unification can't do any harm.

The fact that it works with pdflatex but not with XeLaTeX is not suprising. Probably XeLaTeX emits a PDF construct which pdfsizeopt doesn't understand properly. This needs more investigation.

**Comment by pts** [comment] 2017-06-12 13:24
It looks like the output of XeLaTeX (`myfile.pdf`) is fine, and the bug is either in pdfsizeopt or Ghostscript.

Again, thank you for providing details and example files. `myfile.pdf` is small enough for manual inspection and debugging.

**Comment by pts** [comment] 2017-06-12 16:33
Please upgrade to the latest pdfsizeopt to prevent glyphs from disappearing or changing in `myfile.pso.pdf`.

I've committed 38c310dc2ebaa169531d4cfa8d938cbafb118ba1 as a workaround to prevent font unification (even without `--do-unify-fonts=no`) altogether in this particular case. The underlying problem is the following. The `/Type/Font` object in `myfile.pdf` (generated by XeLaTeX) had the `/Encoding` missing. In this case the built-in encoding of the font should be used. Unfortunately pdfsizeopt is not able to generate a unified Type1C font with the proper built-in encoding, nor it is able to extract the `/Encoding` from the input fonts and specify it explicitly. Implementing these would be a large effort on my part (several days of work), I won't be starting it until I get donations.

**Closed by pts** 2017-06-12 16:33 UTC

**Comment by pts** [comment] 2017-06-12 17:37
Actually I was able to implement generation of `/Encoding` in 34937c6719f573cecb7f6ef3f1e05d1a8628aa95.

Please upgrade to the latest pdfsizeopt and enjoy correct font unification.
