### ISSUE TITLE
KeyError in old pdfsizeopt with encrypted PDF

### ISSUE THREAD

**Issue by rbrito** [pts/pdfsizeopt#27] opened 2017-08-24 02:53 UTC
Hi, @pts.

While using the pdfsizeopt revision 339f049 (and previous ones as well), I get the following crash with a file that was (supposedly, as per pdfinfo) created with pdfTeX:

    info: This is pdfsizeopt rUNKNOWN size=349896.
    info: prepending to PATH: /home/rbrito/Downloads/pdfsizeopt
    info: loading PDF from: futex.pdf
    info: loaded PDF of 244437 bytes
    info: found 220 obj offsets and 2 obj streams in xref stream
    info: separated to 218 objs + xref + trailer
    warning: cannot parse obj 95: pdfsizeopt.main.PdfIndirectLengthError: missing obj for indirect /Length 108 0 R at ofs=18098
    warning: cannot parse obj 110: pdfsizeopt.main.PdfIndirectLengthError: missing obj for indirect /Length 111 0 R at ofs=18846
    warning: cannot parse obj 112: pdfsizeopt.main.PdfIndirectLengthError: missing obj for indirect /Length 121 0 R at ofs=26599
    warning: cannot parse obj 123: pdfsizeopt.main.PdfIndirectLengthError: missing obj for indirect /Length 124 0 R at ofs=27359
    warning: cannot parse obj 126: pdfsizeopt.main.PdfIndirectLengthError: missing obj for indirect /Length 139 0 R at ofs=34875
    warning: cannot parse obj 141: pdfsizeopt.main.PdfIndirectLengthError: missing obj for indirect /Length 142 0 R at ofs=35567
    info: found 11 Type1 fonts loaded

Please, note the warnings above.

(...)

    info: optimized Type1 font XObject 206,205: new size=6118 (40%)
    info: optimized Type1 font XObject 208,207: new size=8523 (43%)
    info: optimized Type1 font XObject 210,209: new size=4973 (37%)
    info: optimized Type1 font XObject 212,211: new size=1889 (29%)
    Traceback (most recent call last):
      File "/home/rbrito/Downloads/pdfsizeopt/pdfsizeopt", line 37, in <module>
        sys.exit(main.main(sys.argv))
      File "/home/rbrito/Downloads/pdfsizeopt/lib/pdfsizeopt/main.py", line 8603, in main
        do_regenerate_all_fonts=do_regenerate_all_fonts)
      File "/home/rbrito/Downloads/pdfsizeopt/lib/pdfsizeopt/main.py", line 6014, in OptimizeType1CFonts
        type1c_objs = self.GetFonts(font_type='Type1C')
      File "/home/rbrito/Downloads/pdfsizeopt/lib/pdfsizeopt/main.py", line 4811, in GetFonts
        font_obj = self.objs[font_obj_num]
    KeyError: 110
    $

The problematic file can be found at: https://www.akkadia.org/drepper/futex.pdf

I don't know if this is a compliant file to the standard or not, though.

Thanks,

Rogério.

**Comment by pts** [comment] 2017-08-24 13:47
Thank you for reporting this!

You must be using an old version of pdfsizeopt (older than 339f049388a8167c87b8b523346c5a5bb7a24669):

```
$ git clone https://github.com/pts/pdfsizeopt/
$ cd pdfsizeopt
$ git checkout 339f049388a8167c87b8b523346c5a5bb7a24669
$ wget -O futex.pdf https://www.akkadia.org/drepper/futex.pdf
$ ./pdfsizeopt futex.pdf
info: This is pdfsizeopt rUNKNOWN size=348915.
info: prepending to PATH: .
info: loading PDF from: futex.pdf
info: loaded PDF of 189828 bytes
info: separated to 213 objs + xref + trailer
Traceback (most recent call last):
  File "./pdfsizeopt", line 37, in <module>
    sys.exit(main.main(sys.argv))
  File "./lib/pdfsizeopt/main.py", line 8572, in main
    ).Load(file_name)
  File "./lib/pdfsizeopt/main.py", line 3453, in Load
    '.decrypted.pdf')))
NotImplementedError: encrypted PDF input not supported, use this command to decrypt first: qpdf --decrypt futex.pdf futex.decrypted.pdf
```
It works after manual decrypting:

```
$ qpdf --decrypt futex.pdf futex.decrypted.pdf
$ ./pdfsizeopt futex.decrypted.pdf
...
info: saving PDF with 195 objs to: futex.decrypted.pso.pdf
info: generated object stream of 5082 bytes in 165 objects (11%)
info: generated 101942 bytes (53%)
```

See https://github.com/pts/pdfsizeopt/issues/25 for making the manual call to qpdf unnecessary.

Closing this bug, because I was not able to reproduce the problem with the latest pdfsizeopt.

**Closed** 2017-08-24 13:48 UTC

**Comment by rbrito** [comment] 2017-08-25 03:23
Oops. You're right. Sorry for misreporting this. I could swear that I double checked it, but it slipped, though.
